treewide: Fix deprecated warning & error causing functions
../net/ipv6/syncookies.c:144:6: warning: unused variable 'full_space' [-Wunused-variable]
        int full_space, mss;
            ^
1 warning generated.

../drivers/gpu/msm/kgsl.c:4937:6: warning: unused variable 'cpu' [-Wunused-variable]
        int cpu;
            ^
1 warning generated.

../drivers/gpu/msm/kgsl_pwrctrl.c:387:15: warning: unused variable 'old_level' [-Wunused-variable]
        unsigned int old_level = pwr->active_pwrlevel;
                     ^
1 warning generated.

../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/hif/src/ce/ce_service_legacy.c:1320:34: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct ce_ops *ce_services_legacy()
                                 ^
                                  void
1 error generated.

../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/target_if/core/src/target_if_main.c:91:40: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct target_if_ctx *target_if_get_ctx()
                                       ^
                                        void
1 error generated.

../techpack/data/drivers/rmnet/perf/rmnet_perf_opt.c:715:27: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
rmnet_perf_free_hash_table()
                          ^
                           void                               1 error generated.

../drivers/nfc/nq-nci.c:1624:31: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
static int lct_check_hwversion()
                              ^
                               void
1 error generated.

Signed-off-by: Excalibur-99 <txexcalibur99@gmail.com>